name: Build pull request
on:
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.8.0
              with:
                  access_token: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Git repository
              uses: actions/checkout@v3
            - name: Setup java
              uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 8
            - name: Build project
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  ./gradlew build jacocoTestReport
                  echo "## Unit Test Coverage" > rapport.md
                  echo "TODO" >> rapport.md
                  echo "## Code Coverage" >> rapport.md
                  echo "TODO" >> rapport.md

            - name: Create comment
              uses: peter-evans/create-or-update-comment@v4
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  body: |
                      # Rapport
                      [Rapport](rapport.md)
                  token: ${{ secrets.GITHUB_TOKEN }}
